# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aghozlane/workspace/MetaboFlux/metaboflux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aghozlane/workspace/MetaboFlux/metaboflux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aghozlane/workspace/MetaboFlux/metaboflux/CMakeFiles /home/aghozlane/workspace/MetaboFlux/metaboflux/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aghozlane/workspace/MetaboFlux/metaboflux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MetaBoFlux.exe

# Build rule for target.
MetaBoFlux.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MetaBoFlux.exe
.PHONY : MetaBoFlux.exe

# fast build rule for target.
MetaBoFlux.exe/fast:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/build
.PHONY : MetaBoFlux.exe/fast

#=============================================================================
# Target rules for targets named html

# Build rule for target.
html: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 html
.PHONY : html

# fast build rule for target.
html/fast:
	$(MAKE) -f doc/CMakeFiles/html.dir/build.make doc/CMakeFiles/html.dir/build
.PHONY : html/fast

src/MetaBoFlux.o: src/MetaBoFlux.c.o
.PHONY : src/MetaBoFlux.o

# target to build an object file
src/MetaBoFlux.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/MetaBoFlux.c.o
.PHONY : src/MetaBoFlux.c.o

src/MetaBoFlux.i: src/MetaBoFlux.c.i
.PHONY : src/MetaBoFlux.i

# target to preprocess a source file
src/MetaBoFlux.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/MetaBoFlux.c.i
.PHONY : src/MetaBoFlux.c.i

src/MetaBoFlux.s: src/MetaBoFlux.c.s
.PHONY : src/MetaBoFlux.s

# target to generate assembly for a file
src/MetaBoFlux.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/MetaBoFlux.c.s
.PHONY : src/MetaBoFlux.c.s

src/data_parameters.o: src/data_parameters.c.o
.PHONY : src/data_parameters.o

# target to build an object file
src/data_parameters.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/data_parameters.c.o
.PHONY : src/data_parameters.c.o

src/data_parameters.i: src/data_parameters.c.i
.PHONY : src/data_parameters.i

# target to preprocess a source file
src/data_parameters.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/data_parameters.c.i
.PHONY : src/data_parameters.c.i

src/data_parameters.s: src/data_parameters.c.s
.PHONY : src/data_parameters.s

# target to generate assembly for a file
src/data_parameters.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/data_parameters.c.s
.PHONY : src/data_parameters.c.s

src/equations.o: src/equations.c.o
.PHONY : src/equations.o

# target to build an object file
src/equations.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/equations.c.o
.PHONY : src/equations.c.o

src/equations.i: src/equations.c.i
.PHONY : src/equations.i

# target to preprocess a source file
src/equations.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/equations.c.i
.PHONY : src/equations.c.i

src/equations.s: src/equations.c.s
.PHONY : src/equations.s

# target to generate assembly for a file
src/equations.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/equations.c.s
.PHONY : src/equations.c.s

src/especes.o: src/especes.c.o
.PHONY : src/especes.o

# target to build an object file
src/especes.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/especes.c.o
.PHONY : src/especes.c.o

src/especes.i: src/especes.c.i
.PHONY : src/especes.i

# target to preprocess a source file
src/especes.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/especes.c.i
.PHONY : src/especes.c.i

src/especes.s: src/especes.c.s
.PHONY : src/especes.s

# target to generate assembly for a file
src/especes.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/especes.c.s
.PHONY : src/especes.c.s

src/gsl_min.o: src/gsl_min.c.o
.PHONY : src/gsl_min.o

# target to build an object file
src/gsl_min.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_min.c.o
.PHONY : src/gsl_min.c.o

src/gsl_min.i: src/gsl_min.c.i
.PHONY : src/gsl_min.i

# target to preprocess a source file
src/gsl_min.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_min.c.i
.PHONY : src/gsl_min.c.i

src/gsl_min.s: src/gsl_min.c.s
.PHONY : src/gsl_min.s

# target to generate assembly for a file
src/gsl_min.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_min.c.s
.PHONY : src/gsl_min.c.s

src/gsl_mod.o: src/gsl_mod.c.o
.PHONY : src/gsl_mod.o

# target to build an object file
src/gsl_mod.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_mod.c.o
.PHONY : src/gsl_mod.c.o

src/gsl_mod.i: src/gsl_mod.c.i
.PHONY : src/gsl_mod.i

# target to preprocess a source file
src/gsl_mod.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_mod.c.i
.PHONY : src/gsl_mod.c.i

src/gsl_mod.s: src/gsl_mod.c.s
.PHONY : src/gsl_mod.s

# target to generate assembly for a file
src/gsl_mod.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_mod.c.s
.PHONY : src/gsl_mod.c.s

src/gsl_recuit.o: src/gsl_recuit.c.o
.PHONY : src/gsl_recuit.o

# target to build an object file
src/gsl_recuit.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_recuit.c.o
.PHONY : src/gsl_recuit.c.o

src/gsl_recuit.i: src/gsl_recuit.c.i
.PHONY : src/gsl_recuit.i

# target to preprocess a source file
src/gsl_recuit.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_recuit.c.i
.PHONY : src/gsl_recuit.c.i

src/gsl_recuit.s: src/gsl_recuit.c.s
.PHONY : src/gsl_recuit.s

# target to generate assembly for a file
src/gsl_recuit.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_recuit.c.s
.PHONY : src/gsl_recuit.c.s

src/gsl_sd.o: src/gsl_sd.c.o
.PHONY : src/gsl_sd.o

# target to build an object file
src/gsl_sd.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_sd.c.o
.PHONY : src/gsl_sd.c.o

src/gsl_sd.i: src/gsl_sd.c.i
.PHONY : src/gsl_sd.i

# target to preprocess a source file
src/gsl_sd.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_sd.c.i
.PHONY : src/gsl_sd.c.i

src/gsl_sd.s: src/gsl_sd.c.s
.PHONY : src/gsl_sd.s

# target to generate assembly for a file
src/gsl_sd.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/gsl_sd.c.s
.PHONY : src/gsl_sd.c.s

src/mpi_load.o: src/mpi_load.c.o
.PHONY : src/mpi_load.o

# target to build an object file
src/mpi_load.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/mpi_load.c.o
.PHONY : src/mpi_load.c.o

src/mpi_load.i: src/mpi_load.c.i
.PHONY : src/mpi_load.i

# target to preprocess a source file
src/mpi_load.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/mpi_load.c.i
.PHONY : src/mpi_load.c.i

src/mpi_load.s: src/mpi_load.c.s
.PHONY : src/mpi_load.s

# target to generate assembly for a file
src/mpi_load.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/mpi_load.c.s
.PHONY : src/mpi_load.c.s

src/simulation.o: src/simulation.c.o
.PHONY : src/simulation.o

# target to build an object file
src/simulation.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/simulation.c.o
.PHONY : src/simulation.c.o

src/simulation.i: src/simulation.c.i
.PHONY : src/simulation.i

# target to preprocess a source file
src/simulation.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/simulation.c.i
.PHONY : src/simulation.c.i

src/simulation.s: src/simulation.c.s
.PHONY : src/simulation.s

# target to generate assembly for a file
src/simulation.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/simulation.c.s
.PHONY : src/simulation.c.s

src/xml_parameter.o: src/xml_parameter.c.o
.PHONY : src/xml_parameter.o

# target to build an object file
src/xml_parameter.c.o:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/xml_parameter.c.o
.PHONY : src/xml_parameter.c.o

src/xml_parameter.i: src/xml_parameter.c.i
.PHONY : src/xml_parameter.i

# target to preprocess a source file
src/xml_parameter.c.i:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/xml_parameter.c.i
.PHONY : src/xml_parameter.c.i

src/xml_parameter.s: src/xml_parameter.c.s
.PHONY : src/xml_parameter.s

# target to generate assembly for a file
src/xml_parameter.c.s:
	$(MAKE) -f CMakeFiles/MetaBoFlux.exe.dir/build.make CMakeFiles/MetaBoFlux.exe.dir/src/xml_parameter.c.s
.PHONY : src/xml_parameter.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MetaBoFlux.exe"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... html"
	@echo "... src/MetaBoFlux.o"
	@echo "... src/MetaBoFlux.i"
	@echo "... src/MetaBoFlux.s"
	@echo "... src/data_parameters.o"
	@echo "... src/data_parameters.i"
	@echo "... src/data_parameters.s"
	@echo "... src/equations.o"
	@echo "... src/equations.i"
	@echo "... src/equations.s"
	@echo "... src/especes.o"
	@echo "... src/especes.i"
	@echo "... src/especes.s"
	@echo "... src/gsl_min.o"
	@echo "... src/gsl_min.i"
	@echo "... src/gsl_min.s"
	@echo "... src/gsl_mod.o"
	@echo "... src/gsl_mod.i"
	@echo "... src/gsl_mod.s"
	@echo "... src/gsl_recuit.o"
	@echo "... src/gsl_recuit.i"
	@echo "... src/gsl_recuit.s"
	@echo "... src/gsl_sd.o"
	@echo "... src/gsl_sd.i"
	@echo "... src/gsl_sd.s"
	@echo "... src/mpi_load.o"
	@echo "... src/mpi_load.i"
	@echo "... src/mpi_load.s"
	@echo "... src/simulation.o"
	@echo "... src/simulation.i"
	@echo "... src/simulation.s"
	@echo "... src/xml_parameter.o"
	@echo "... src/xml_parameter.i"
	@echo "... src/xml_parameter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

